baseURL = "/"
theme = "renekann.de"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = "EN"
    weight = 1
    contactEndpoint = "https://app.99inbound.com/api/e/Yt0LOhWn"
    honeypot = "excellent_taupe_satin_toad"
    siteDescription = "I am a software engineer with many years of experience for Mobile (iOS / Flutter) and web, including knowledge of the \"full-stack\" of web technologies for frontend and backend services."

  [languages.de]
    languageName = "DE"
    weight = 2
    contactEndpoint = "https://app.99inbound.com/api/e/09UD9P5C"
    honeypot = "free_range_coral_houndstooth_sand"
    siteDescription = "Ich bin ein Software-Ingenieur mit langjähriger Erfahrung für Mobile (iOS / Flutter) und Web, einschließlich der Kenntnisse des \"Full-Stacks\" von Web-Technologien für Frontend- und Backend-Services."

[params]
  title = "René Kann - Senior Mobile Developer in Berlin (native iOS / Flutter)"
  favicon = "favicon.png"
  metaImage = "avatar.jpg"

[params.nav]
  enable = true

[params.profile]
  enable = true
  anchor = "about"

[params.quotes]
  enable = true

[params.skills]
  enable = true
  anchor = "skills"

[params.work]
  enable = true
  anchor = "work"

[params.clients]
  enable = false
  anchor = "clients"

[params.services]
  enable = false
  title = "How I can help"
  title_menu = "Services"

[params.languages]
  enable = true
  title = "Languages"

[params.education]
  enable = true
  title = "Education"

[params.contact]
  enable = true
  anchor = "contact"

[params.footer]
  enable = true
