baseURL = "/"
theme = "renekann.de"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = "EN"
    weight = 1
    contactEndpoint = "https://app.99inbound.com/api/e/Yt0LOhWn"
    honeypot = "excellent_taupe_satin_toad"
  [languages.de]
    languageName = "DE"
    weight = 2
    contactEndpoint = "https://app.99inbound.com/api/e/09UD9P5C"
    honeypot = "free_range_coral_houndstooth_sand"
    
[params]
  title = "Ren√© Kann - Senior iOS Developer / Mobile developer in Berlin"
  favicon = "favicon.png"
    
[params.nav]
  enable = true

[params.profile]
  enable = true
  anchor = "about"

[params.skills]
  enable = true
  anchor = "skills"

[params.work]
  enable = true
  anchor = "work"
  
[params.services]
  enable = false
  title = "How I can help"
  title_menu = "Services"

[params.languages]
  enable = true
  title = "Languages"

[params.education]
  enable = true
  title = "Education"
  
[params.contact]
  enable = true
  anchor = "contact"

[params.footer]
  enable = true