baseURL = "https://www.renekann.de"
languageCode = "en-us"
theme = "renekann.de"
DefaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "René Kann - Senior iOS Developer / Mobile developer in Berlin"
  [languages.de]
    title = "René Kann - Senior iOS Developer / Mobile developer in Berlin"

[params]
  favicon = "favicon.png"
  logo = "logo.png"
    
[params.nav]
  enable = true

[params.profile]
  enable = true
  resume = "resume.pdf"
  resume_word ="resume-word.doc"
  title_menu = "About"
  anchor = "about"

[params.skills]
  enable = true
  title = "Skills"
  title_menu = "Skills"
  anchor = "skills"

[params.work]
  enable = true
  title = "My Work"
  title_menu = "Work"
  anchor = "work"
  
[params.services]
  enable = false
  title = "How I can help"
  title_menu = "Services"

[params.languages]
  enable = true
  title = "Languages"
  title_menu = "Languages"

[params.education]
  enable = true
  title = "Education"
  title_menu = "Education"
  
[params.contact]
  enable = true
  title = "Contact"
  title_menu = "Contact"
  working_together = "Interested to work together? Let's talk"
  anchor = "contact"

[params.footer]
  enable = true